server: # REST and WS server
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.6.0"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.0" # adding youtube plugin
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false # this is deprecated so we are using the plugin instead
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: false

plugins:
  lavasrc:
    providers: # Custom providers for track loading. This is the default
      # - "dzisrc:%ISRC%" # Deezer ISRC provider
      # - "dzsearch:%QUERY%" # Deezer search provider
      - "ytsearch:\"%ISRC%\"" # Will be ignored if track does not have an ISRC. See https://en.wikipedia.org/wiki/International_Standard_Recording_Code
      - "ytsearch:%QUERY%" # Will be used if track has no ISRC or no track could be found for the ISRC
      #  you can add multiple other fallback sources here
    sources:
      spotify: true
    spotify:
      clientId: ${LAVALINK_PLUGIN_SPOTIFY_CLIENT_ID}
      clientSecret: ${LAVALINK_PLUGIN_SPOTIFY_CLIENT_SECRET}
      # spDc: "your sp dc cookie" # the sp dc cookie used for accessing the spotify lyrics api
      countryCode: "US" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
      resolveArtistsInSearch: true # Whether to resolve artists in track search results (can be slow)
      localFiles: false # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    oauth:
      # setting "enabled: true" is the bare minimum to get OAuth working.
      enabled: true   
      refreshToken: ${LAVALINK_PLUGIN_YOUTUBE_REFRESH_TOKEN}
      skipInitialization: true
