name: Lint and Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, development]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js v12.16.3
              uses: actions/setup-node@v1
              with:
                  node-version: 12.16.3
            - name: Install dependencies
              run: npm ci

            - name: Set command prefix in env
              run: |
                  # Needed for help test snapshots
                  touch .env
                  echo 'PREFIX="-"' >> .env

            - name: Check for linting errors
              run: npm run lint
